## Terraform Makefile

# Terraform variables

TF_DIR := terraform
TF_PLAN := $(TF_DIR)/terraform.tfplan

plan:
	@echo "Terraform Plan"
	@terraform plan

apply:
	@echo "Terraform Apply"
	@terraform apply

destroy:
	@echo "Terraform Destroy"
	@terraform destroy